[workspace]
resolver = "2"

members = [
    "numbat",
    "numbat-exchange-rates",
    "numbat-cli",
    "numbat-lsp",
]

exclude = [
    "numbat-wasm"
]

[profile.release]
# lto = true
# strip = true
# codegen-units = 1
